server:
  port: 8761
spring:
  application:
    name: discovery-service

eureka:
  client:
    register-with-eureka: false
    fetch-repository: false
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
  hostname: localhost
