server:
  port: 8080
  application:
    name: gateway-service

spring:
  application:
    name: gateway-servicee

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5

jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY
